menu:
  Home: /
  Archives: /archives/
  About: /about/
  Subscribe: /atom.xml

gallery:
  Gallery: //t.xudshen.info

widgets: 
- menu
- tagcloud
- gallery
- search

excerpt_link: Read More

fancybox: true

# 友言评论
UYUserId:

# cnzz统计
cnzzId: 1253420162

# JiaThis分享
jiathisUUID:

weibo:
	name:
	uid:
	link:

twitter:
	name: xudshen
	link: https://twitter.com/xudshen

rss: /atom.xml