menu:
  Home: /
  Archives: /archives/
  About: /about/
  Subscribe: /atom.xml

widgets: 
- menu
- tagcloud
- search

excerpt_link: Read More

fancybox: true

# 友言评论
UYUserId:

# cnzz统计
cnzzId:

# JiaThis分享
jiathisUUID:

weibo:
	name:
	uid:
	link:

twitter:
	name: xudshen
	link: https://twitter.com/xudshen

rss: http://xudshen.info/atom.xml